import enum


class UserRole(str, enum.Enum):
    IMPORTER = "importer"
    AGENT = "agent"
    AGENCY_MANAGER = "agency_manager"
    INSPECTOR = "inspector"
    GOVERNMENT_RRA = "government_rra"
    GOVERNMENT_RSB = "government_rsb"
    ADMIN = "admin"


class AgencyRole(str, enum.Enum):
    MANAGER = "manager"
    AGENT = "agent"


class AuthAction(str, enum.Enum):
    SIGNUP = "SIGNUP"
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    FAILED_LOGIN = "FAILED_LOGIN"
    EMAIL_VERIFY = "EMAIL_VERIFY"
    INVITATION_SENT = "INVITATION_SENT"
    INVITATION_USED = "INVITATION_USED"
    INVITATION_REVOKED = "INVITATION_REVOKED"
    INVITATION_RESENT = "INVITATION_RESENT"
    PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED"
    PASSWORD_RESET = "PASSWORD_RESET"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    ACCOUNT_UNLOCKED = "ACCOUNT_UNLOCKED"
    PROFILE_UPDATED = "PROFILE_UPDATED"
    ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED"
    ACCOUNT_ACTIVATED = "ACCOUNT_ACTIVATED"
    TOKEN_REFRESH = "TOKEN_REFRESH"
    ADMIN_CREATED = "ADMIN_CREATED"
    AGENCY_CREATED = "AGENCY_CREATED"
    SHADOW_START = "SHADOW_START"
    SHADOW_END = "SHADOW_END"
